// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1HahHySXBJZhJYm8Cn6bBValH39w_3I',
    appId: '1:325384984044:web:7efbbdf93256697552dcc9',
    messagingSenderId: '325384984044',
    projectId: 'hakistore-93f57',
    authDomain: 'hakistore-93f57.firebaseapp.com',
    storageBucket: 'hakistore-93f57.appspot.com',
    measurementId: 'G-2KVRNH72JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFdDgOLS9CbLvAX37PeU6GZLrgyCJt9hY',
    appId: '1:325384984044:android:545f1615540fdf2152dcc9',
    messagingSenderId: '325384984044',
    projectId: 'hakistore-93f57',
    storageBucket: 'hakistore-93f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAGj6Lmj4hqr9IUQQ6fpmq5daRa_Llb2g',
    appId: '1:325384984044:ios:f64457d53fc1ca4d52dcc9',
    messagingSenderId: '325384984044',
    projectId: 'hakistore-93f57',
    storageBucket: 'hakistore-93f57.appspot.com',
    iosBundleId: 'com.example.bangiayhaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAGj6Lmj4hqr9IUQQ6fpmq5daRa_Llb2g',
    appId: '1:325384984044:ios:85e71ee52f2fe44e52dcc9',
    messagingSenderId: '325384984044',
    projectId: 'hakistore-93f57',
    storageBucket: 'hakistore-93f57.appspot.com',
    iosBundleId: 'com.example.bangiayhaki.RunnerTests',
  );
}
